---
- name: Install supervisord
  ansible.builtin.apt:
    pkg: supervisor
    state: present

- name: Create supervisord group
  ansible.builtin.group:
    name: supervisord
    system: "yes"
    state: present

- name: Add the supervisor fatals events listener
  ansible.builtin.copy:
    src: files/supervisor-fatals-listener.py
    mode: "0755"
    dest: /usr/local/bin/supervisor-fatals-listener.py
  when: supervisord_log_fatal_state_to_syslog

- name: Configure the supervisor fatals events listener
  ansible.builtin.template:
    src: "files/supervisor.event.listeners.conf.j2"
    dest: "/etc/supervisor/conf.d/eventlisteners.conf"
    mode: "0644"
  when: supervisord_log_fatal_state_to_syslog

- name: Create supervisord config
  ansible.builtin.template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
    mode: "0644"
  register: supervisord_config_file
  notify: Restart supervisord

- name: Start supervisord
  ansible.builtin.service:
    name: supervisor
    state: started
    enabled: "yes"
