---
- name: Reload supervisord configuration
  ansible.builtin.command: "supervisorctl reread"
  notify: Apply supervisord changes
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Apply supervisord changes
  ansible.builtin.command: "supervisorctl update" # noqa
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Restart supervisord
  ansible.builtin.service:
    name: supervisor
    state: restarted
